### ISSUE TITLE
Uprade jasmine 2 version 

### ISSUE THREAD

**Issue by SanityResort** [joescii/sbt-jasmine-plugin#10]
I came across a bug within jasmine which seems to have been fixed with a new version, so it might be a good idea to upgrade to the current jasmine 2 version.

For reference, see the issue here: https://github.com/jasmine/jasmine/issues/913

**Comment by joescii** [comment]
Thanks for raising this issue.  FWIW, I hope to soon change sbt-jasmine-plugin to get its jasmine js from web-jars.  That'll make it possible for users to update the jasmine version independently.

**Comment by joescii** [comment]
As of 1.4.0, you can now provide your own jasmine webjar to get the version of jasmine you like.
